services:
 zookeeper:
   image: confluentinc/cp-zookeeper:7.4.4
   restart: always
   container_name: zookeeper
   hostname: zookeeper
   ports:
     - "2181:2181"
   volumes:
     - data-zookeeper-log-1:/var/lib/zookeeper/log
     - data-zookeeper-data-1:/var/lib/zookeeper/data
     - ./jaas_conf_zoo/zookeeper_server_jaas.conf:/opt/zoo/zookeeper_server_jaas.conf
   networks:
     - confluent
   environment:
     ZOOKEEPER_SERVER_ID: 1
     ZOOKEEPER_CLIENT_PORT: 2181
     ZOOKEEPER_TICK_TIME: 2000
     ZOOKEEPER_INIT_LIMIT: 5
     ZOOKEEPER_SYNC_LIMIT: 2
     KAFKA_OPTS:
       -Djava.security.auth.login.config=/opt/zoo/zookeeper_server_jaas.conf
       -Dquorum.auth.enableSasl=true
       -Dquorum.cnxn.threads.size=20
       -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
       -DjaasLoginRenew=3600000
       -DrequireClientAuthScheme=sasl

 kafka-0:
   image: confluentinc/cp-kafka:7.4.4
   restart: always
   container_name: kafka-0
   hostname: kafka-0
   depends_on:
     - zookeeper
   ports:
     - "9096:9096"
     - "29096:29096"
   networks:
     - confluent
   volumes:
     - data-kafka-0:/var/lib/kafka/data
     - ./kafka-0-creds:/etc/kafka/secrets
     - ./reassignment:/opt/reassignment
     - ./jaas_conf/kafka_server_jaas.conf:/opt/kafka/kafka_server_jaas.conf
   environment:
     KAFKA_BROKER_ID: 0
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
     KAFKA_DELETE_TOPIC_ENABLE: true
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_LISTENERS: PLAINTEXT://:29096,SSL://:9096
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-0:29096,SSL://localhost:9096
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
     KAFKA_LISTENER_SECURITY_PROTOCOL: SSL
     KAFKA_SSL_KEYSTORE_FILENAME: kafka-0.keystore.jks
     KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-0_ssl_pwd
     KAFKA_SSL_KEY_CREDENTIALS: kafka-0_ssl_pwd
     KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka-0.truststore.jks
     KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-0_ssl_pwd
     KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
     KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.authorizer.AclAuthorizer"
     KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/kafka_server_jaas.conf"

 kafka-1:
   image: confluentinc/cp-kafka:7.4.4
   restart: always
   container_name: kafka-1
   hostname: kafka-1
   depends_on:
     - zookeeper
   ports:
     - "9093:9093"
     - "29093:29093"
   networks:
     - confluent
   volumes:
     - data-kafka-1:/var/lib/kafka/data
     - ./kafka-1-creds:/etc/kafka/secrets
     - ./reassignment:/opt/reassignment
      - ./jaas_conf/kafka_server_jaas.conf:/opt/kafka/kafka_server_jaas.conf
   environment:
     KAFKA_BROKER_ID: 1
     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
     KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
     KAFKA_DELETE_TOPIC_ENABLE: true
     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
     KAFKA_LISTENERS: PLAINTEXT://:29093,SSL://:9093
     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:29093,SSL://localhost:9093
     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
     KAFKA_LISTENER_SECURITY_PROTOCOL: SSL
     KAFKA_SSL_KEYSTORE_FILENAME: kafka-1.keystore.jks
     KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-1_ssl_pwd
     KAFKA_SSL_KEY_CREDENTIALS: kafka-1_ssl_pwd
     KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka-1.truststore.jks
     KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-1_ssl_pwd
     KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
     KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.authorizer.AclAuthorizer"
     KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/kafka_server_jaas.conf"

 kafka-2:
     image: confluentinc/cp-kafka:7.4.4
     restart: always
     container_name: kafka-2
     hostname: kafka-2
     depends_on:
       - zookeeper
     ports:
       - "9092:9092"
       - "29092:29092"
     networks:
       - confluent
     volumes:
       - data-kafka-2:/var/lib/kafka/data
       - ./kafka-2-creds:/etc/kafka/secrets
       - ./reassignment:/opt/reassignment
       - ./jaas_conf/kafka_server_jaas.conf:/opt/kafka/kafka_server_jaas.conf
     environment:
       KAFKA_BROKER_ID: 2
       KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
       KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
       KAFKA_DELETE_TOPIC_ENABLE: true
       KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
       KAFKA_LISTENERS: PLAINTEXT://:29092,SSL://:9092
       KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:29092,SSL://localhost:9092
       KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,SSL:SSL
       KAFKA_LISTENER_SECURITY_PROTOCOL: SSL
       KAFKA_SSL_KEYSTORE_FILENAME: kafka-2.keystore.jks
       KAFKA_SSL_KEYSTORE_CREDENTIALS: kafka-2_ssl_pwd
       KAFKA_SSL_KEY_CREDENTIALS: kafka-2_ssl_pwd
       KAFKA_SSL_TRUSTSTORE_FILENAME: kafka.kafka-2.truststore.jks
       KAFKA_SSL_TRUSTSTORE_CREDENTIALS: kafka-2_ssl_pwd
       KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: https
       KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.authorizer.AclAuthorizer"
       KAFKA_OPTS: "-Djava.security.auth.login.config=/opt/kafka/kafka_server_jaas.conf"
volumes:
 data-zookeeper-log-1:
 data-zookeeper-data-1:
 data-kafka-0:
 data-kafka-1:
 data-kafka-2:

networks:
 confluent:


